[project]
name = "tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi-cli>=0.0.5",
    "fastapi[standart]>=0.115.0",
]
